// app/data.js
export const items = [
  {
    id: 1,
    name: "Hogwarts Legacy",
    blurb:
      "The wizarding world awaits you. Freely roam Hogwarts, Hogsmeade, the Forbidden Forest, and the surrounding Overland area.",
    rating: 5,
    image: "/hogwarts.jpg",
    emoji: "🏰",
  },
  {
    id: 2,
    name: "Hollow Knight",
    blurb:
      "Step into the ultimate shooter experience where modern battles never stop!",
    rating: 5,
    image: "/hollowknight.jpg",
    emoji: "🛡️",
  },
  {
    id: 3,
    name: "Forza Horizon 5",
    blurb: "Build your dream creations using the upgraded EventLab toolset, capture your favorite cars with enhanced Photo Mode, or test your driving skills in Hide & Seek and Horizon Realms.",
    rating: 4,
    image: "/forza-horizon.jpeg",
    emoji: "🚘",
  },
  {
    id: 4,
    name: "Gothic",
    blurb: "The Legend is Back - Return to the Valley of the Mines in this faithful remake of the genre-defining classic RPG.",
    rating: 4,
    image: "/gothic.png",
    emoji: "💀",
  },
  {
    id: 5,
    name: "Resident evil 4",
    blurb: "A reimagined storyline, and vividly detailed graphics, Resident Evil 4 marks the rebirth of an industry juggernaut.",
    rating: 4,
    image:"/resident-evil.png",
    emoji: "🦹🏻‍♀️",
  },
  {
    id: 6,
    name: "Dead by daylight",
    blurb: "Trapped forever in a realm of eldritch evil where even death is not an escape, four determined Survivors face a bloodthirsty Killer in a...",
    rating: 4,
    image: "/dead-by-daylight-pc-steam-cover.jpg",
    emoji: "🪦",
  },
  {
    id: 7,
    name: "Rivals",
    blurb: "detective game about piecing together the events surrounding two fictional musicians. The music samples and voice ...",
    rating: 4,
    image: "/rivals.jpg",
    emoji: "🚨",
  },
  {
    id: 8,
    name: "Pubg Battlegrounds",
    blurb: "A battle royale that pits 100 players against each other. Outplay your opponents.",
    rating: 4,
    image: "/pubg.jpg",
    emoji: "🚁",
  },
  {
    id: 8,
    name: "Counter Strike",
    blurb: "Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game",
    rating: 4,
    image: "/counter-strike.jpeg",
    emoji: "🌩️",
  },
  {
    id: 9,
    name: "Hunt",
    blurb: "Set in the darkest corners of the world, Hunt packs the thrill ...",
    rating: 4,
    image: "/hunt.jpeg",
    emoji: "🌩️",
  },
  {
    id: 10,
    name: "Village : Resident Evil",
    blurb: "The next generation of survival horror rises in the form of Resident Evil Village, the eighth major entry in the Resident Evil series",
    rating: 4,
    image: "/village.jpeg",
    emoji: "🌩️",
  },
  {
    id: 11,
    name: "Path of exile",
    blurb: "Set in the dark fantasy world of Wraeclast. ",
    rating: 4,
    image: "/path-of-exile.jpg",
    emoji: "🌩️",
  },
];
